# Generated by Django 3.2.22 on 2023-11-01 00:12

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputQueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=300)),
                ('user_voice', models.FileField(blank=True, null=True, upload_to=home.models.voice_upload_path)),
                ('search_query', models.CharField(blank=True, max_length=200, null=True)),
                ('product_qty', models.IntegerField(default=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('specs', models.CharField(blank=True, max_length=50, null=True)),
                ('image_bytes', models.TextField(blank=True, null=True)),
                ('estimated_price', models.CharField(blank=True, max_length=50, null=True)),
                ('input_query_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_data_model', to='home.inputquerymodel')),
            ],
        ),
    ]
